[package]
name = "system-constants-generator"
version = "0.1.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
description = "Tool for generating JSON files with the system constants for L1/L2 contracts"
publish = false # We don't want to publish our binaries.

[dependencies]
zksync_state = { path = "../../lib/state" }
zksync_types = { path = "../../lib/types" }
zksync_utils = { path = "../../lib/utils" }
zksync_contracts = { path = "../../lib/contracts" }
multivm = { path = "../../lib/multivm" }
codegen = "0.2.0"
# This is not correct - we should migrated to 1.4.1
zkevm_opcode_defs = { git = "https://github.com/matter-labs/era-zkevm_opcode_defs.git", branch="v1.3.2"}

serde = "1.0"
serde_json = "1.0"
once_cell = "1.7"
