[package]
name = "erc20_fetcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpsee = { version = "0.21.0", features = [
    "macros", "server", "http-client"
] }
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
clap = { version = "4.2.4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
futures = "0.3"
reqwest = { version = "0.11", features = ["json", "blocking"] }
