version: '3.2'
services:
#  geth:
#    image: "ethereum/client-go:v1.13.5"
#    ports:
#      - 8551:8551
#      - 8545:8545
#      - 8546:8546
#    volumes:
#      - ./volumes/geth:/var/lib/geth/data
#      - ./docker/geth/:/geth/:ro
#    command:
#      - --networkid=9
#      - --datadir=/var/lib/geth/data
#      - --http
#      - --http.api=engine,eth,web3,personal,net,debug
#      - --http.addr=0.0.0.0
#      - --http.corsdomain=*
#      - --http.vhosts=*
#      - --ws
#      - --ws.addr=0.0.0.0
#      - --ws.port=8546
#      - --ws.origins=*
#      - --nodiscover
#      - --authrpc.addr=0.0.0.0
#      - --authrpc.vhosts=*
#      - --authrpc.jwtsecret=/var/lib/geth/data/jwtsecret
#      - --allow-insecure-unlock
#      - --unlock=0x8a91dc2d28b689474298d91899f0c1baf62cb85b
#      - --password=/var/lib/geth/data/password.sec
#      - --syncmode=full
  reth:
    restart: always
    image: "ghcr.io/paradigmxyz/reth:v0.1.0-alpha.21"
    volumes:
      - type: bind
        source: ./volumes/reth/data
        target: /rethdata
      - type: bind
        source: ./volumes/reth/logs
        target: /rethlogs
    command: node --dev --datadir /rethdata --http --http.port 8545 --http.addr 0.0.0.0

    ports:
      - 127.0.0.1:8545:8545
  postgres:
    image: "postgres:14"
    command: postgres -c 'max_connections=200'
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - type: bind
        source: ./volumes/postgres
        target: /var/lib/postgresql/data
    environment:
      # We bind only to 127.0.0.1, so setting insecure password is acceptable here
      - POSTGRES_PASSWORD=notsecurepassword

  # This is specific to runner
  zk:
    image: "matterlabs/zk-environment:latest2.0-lightweight"
    security_opt:
      - seccomp:unconfined
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/zksync
      - /usr/src/cache:/usr/src/cache
      - /var/run/docker.sock:/var/run/docker.sock
      - ./hardhat-nodejs:/root/.cache/hardhat-nodejs
    environment:
      - CACHE_DIR=/usr/src/cache
      - SCCACHE_CACHE_SIZE=50g
      - SCCACHE_GCS_BUCKET=matterlabs-infra-sccache-storage
      - SCCACHE_GCS_SERVICE_ACCOUNT=gha-ci-runners@matterlabs-infra.iam.gserviceaccount.com
      - SCCACHE_ERROR_LOG=/tmp/sccache_log.txt
      - SCCACHE_GCS_RW_MODE=READ_WRITE
      - CI=1
      - GITHUB_WORKSPACE=$GITHUB_WORKSPACE
    env_file:
      - ./.env
    extra_hosts:
      - "host:host-gateway"
    profiles:
      - runner
