[package]
name = "zksync_batch_verifier"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
zksync_tee_verifier.workspace = true
zksync_object_store.workspace = true
zksync_config.workspace = true
zksync_basic_types.workspace = true
anyhow.workspace = true
