[package]
name = "zk_supervisor"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
authors.workspace = true
exclude.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true

[dependencies]
alloy-primitives.workspace = true
anyhow.workspace = true
clap.workspace = true
cliclack.workspace = true
config.workspace = true
console.workspace = true
human-panic.workspace = true
serde_yaml.workspace = true
serde.workspace = true
serde_json.workspace = true
xshell.workspace = true
ethers.workspace = true
common.workspace = true
tokio.workspace = true
strum_macros.workspace = true
strum.workspace = true
toml.workspace = true
url.workspace = true
thiserror.workspace = true
