__imports__ = [
    "base",
    "l1-inits/sepolia-shared-bridge.env",
    "l2-inits/sepolia-chain.init.env",
]
ZKSYNC_DEBUG_LOGS = true
CHAIN_ETH_NETWORK = "sepolia"
ETH_CLIENT_CHAIN_ID = 11155111
CONTRACTS_L1_WETH_TOKEN_ADDR = 0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9
DATABASE_URL = "postgres://postgres@localhost/sepolia-chain"

# Fill these out: 
CHAIN_ETH_ZKSYNC_NETWORK_ID = 280
GOVERNOR_ADDRESS = 0x0
GOVERNOR_PRIVATE_KEY = "0x"
DEPLOYER_PRIVATE_KEY = "0x"
ETH_CLIENT_WEB3_URL = "https://eth-sepolia.g.alchemy.com/v2/[API-KEY]"
ETH_SENDER_SENDER_OPERATOR_COMMIT_ETH_ADDR = 0x0
ETH_SENDER_SENDER_OPERATOR_PRIVATE_KEY = "0x"
# If you have etherscan api key. Otherwise leave it commented out,
# otherwise process will fail.
# MISC_ETHERSCAN_API_KEY=[API-KEY]

# These pricing params may have to be adjusted if the server throws
# warnings about underpriced txs
ETH_SENDER_GAS_ADJUSTER_PRICING_FORMULA_PARAMETER_A = 2.5
ETH_SENDER_GAS_ADJUSTER_PRICING_FORMULA_PARAMETER_B = 1.1
