[package]
name = "zksync_tee_prover"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
zksync_config.workspace = true
zksync_env_config.workspace = true
zksync_protobuf_config.workspace = true
zksync_storage.workspace = true
zksync_utils.workspace = true
zksync_types.workspace = true
zksync_core.workspace = true
zksync_object_store.workspace = true
zksync_tee_verifier.workspace = true
google-cloud-pubsub.workspace = true
google-cloud-auth.workspace = true

# Consensus dependenices
zksync_consensus_crypto.workspace = true
zksync_consensus_roles.workspace = true
zksync_consensus_executor.workspace = true
zksync_concurrency.workspace = true
vlog.workspace = true

anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
futures.workspace = true
futures-util = "0.3"
[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator.workspace = true
