name: Check JSON RPC for External Node Snapshot Recovery
on:
  pull_request:


jobs:
  prepare_env:
    runs-on: [matterlabs-ci-runner]
    env:
      SERVER_COMPONENTS: "api,tree,eth,state_keeper,housekeeper,commitment_generator"

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          submodules: "recursive"
        
      - name: Setup environment
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH
          echo IN_DOCKER=1 >> .env
          cat .env

      - name: Start services
        run: |
          ci_localnet_up
          ci_run sccache --start-server

      - name: Run zk init
        run: |
          ci_run git config --global --add safe.directory /usr/src/zksync
          ci_run git config --global --add safe.directory /usr/src/zksync/sdk/binaryen
          ci_run git config --global --add safe.directory /usr/src/zksync/contracts/system-contracts
          ci_run git config --global --add safe.directory /usr/src/zksync/contracts
          ci_run zk
          ci_run zk init
 
      - name: Run main node
        run: |
          ci_run zk server --uring --components=$SERVER_COMPONENTS &>server.log &
          ci_run sleep 30

      - name: Setup environment
        run: |
          echo EXPECTED_TX_COUNT="1000" >> .env
          echo EXPECTED_TX_COUNT="1000" >> $GITHUB_ENV
          echo FAIL_FAST=true >> .env
          echo DATABASE_MERKLE_TREE_MODE=lightweight >> .env
          cat .env

      - name: Perform loadtest
        run: |
          EXPECTED_TX_COUNT=1000 ACCOUNTS_AMOUNT=40 DURATION_SEC=30 FAIL_FAST=true ci_run zk run loadtest
             
      - name: Step - Create a snapshot
        if: always()
        run: |
          ci_run zk env docker
          ci_run zk run snapshots-creator

      - name: Setup environment
        run: |
          echo ZKSYNC_ENV=ext-node >> .env
          echo ZKSYNC_ENV=ext-node >> $GITHUB_ENV

      - name: Step - Run external node
        if: always()
        run: |
          ci_run zk config compile ext-node
          ZKSYNC_ENV=ext-node ci_run zk external-node --reinit -- --enable-snapshots-recovery &
          ci_run sleep 10

      - name: Step - Stub - Try a curl request
        if: always()
        run: |
          curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc": "2.0", "id": 1, "method": "zks_getBlockDetails", "params": [ 1 ]}'  "http://localhost:3060"
